version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.9
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    command: >
      sh -c "pip install --no-cache-dir -r /workspace/src/requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

    network_mode: service:db

    environment:
      DATABASE_URL: postgresql+psycopg2://app_user:app_password@db/app
      JWT_SECRET_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IntcbiAgIFwiaXNzXCI6IFwibXlfaXNzdXJlclwiLFxuICAgXCJpYXRcIjogMTQwMDA2MjQwMDIyMyxcbiAgIFwidHlwZVwiOiBcIi9vbmxpbmUvc3RhdHVzL3YyXCIsXG4gICBcInJlcXVlc3RcIjoge1xuICAgICBcInRyYW5zYWN0aW9uX2lkXCI6IFwidHJhXzc0MzQ3MDgyXCIsXG4gICAgIFwibWVyY2hhbnRfaWRcIjogXCJtZXJjX2E3MTQxdXRuYTg0XCIsXG4gICAgIFwic3RhdHVzXCI6IFwiU1VDQ0VTU1wiXG4gICB9XG4gfSI.U-W6AF8IPyatr8s9VXkZIb2LOJPu0GjNXss8kRfC610
      JWT_REFRESH_SECRET_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IntcbiAgIFwiaXNzXCI6IFwibXlfaXNzdXJlclwiLFxuICAgXCJpYXRcIjogMTQwMDA2MjQwMDIyMyxcbiAgIFwidHlwZVwiOiBcIi9vbmxpbmUvc3RhdHVzL3YyXCIsXG4gICBcInJlcXVlc3RcIjoge1xuICAgICBcInRyYW5zYWN0aW9uX2lkXCI6IFwidHJhXzc0MzQ3MDgyXCIsXG4gICAgIFwibWVyY2hhbnRfaWRcIjogXCJtZXJjX2E3MTQxdXRuYTg0XCIsXG4gICAgIFwic3RhdHVzXCI6IFwiU1VDQ0VTU1wiXG4gICB9XG4gfSI.6jRuw7bhl1H5e55nben2oPhF1u8zJXYvBxbPbtmWH1g

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app_password

volumes:
  postgres-data: